- name: Install dnsmasq 
  apt:
    name: [ "dnsmasq" ]
    state: present

- name: Install config for dnsmasq
  template:
    src: "{{item}}.j2"
    dest:  "/etc/{{item}}"
    mode:  644 
    owner: root 
    group: root 
  with_items: 
    - dnsmasq.conf
    - resolv.conf
  notify: restart dnsmasq
    
- name: Disable systemd resolver
  systemd:
    name: systemd-resolved
    state: stopped 
    enabled: false

- name: Enable systemd 
  systemd:
    name: dnsmasq 
    enabled: true 
